# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Build
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Check out
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
    - name: Print conda info without the bash -l {0} command
      run: |
        conda info
        conda list
    - name: Print conda info with the bash -l {0} command
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Test library available with the bash -l {0} command
      shell: bash -l {0}
      run: |
        python test_numpy_available.py
    - name: Test library available without the bash -l {0} command
      run: |
        python test_numpy_available.py
